---
language: go

env:
  global:
    CLI_NAME: change-all-stacks
    PATH: $PATH:$GOPATH/bin

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - make test

before_deploy:
  - make BUILD_DIR=. all

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: Version ${TRAVIS_TAG/v/}
  file:
    - ${CLI_NAME}-linux
    - ${CLI_NAME}-darwin
    - ${CLI_NAME}-windows.exe
  skip_cleanup: true
  on:
    tags: true
