// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/change-all-stacks/change"
	"github.com/mike-carey/change-all-stacks/query"
)

type FakeInquisitorManager struct {
	GetHelperStub        func(*cfclient.Config) (change.InquisitorHelper, error)
	getHelperMutex       sync.RWMutex
	getHelperArgsForCall []struct {
		arg1 *cfclient.Config
	}
	getHelperReturns struct {
		result1 change.InquisitorHelper
		result2 error
	}
	getHelperReturnsOnCall map[int]struct {
		result1 change.InquisitorHelper
		result2 error
	}
	GetInquisitorStub        func(*cfclient.Config) (query.Inquisitor, error)
	getInquisitorMutex       sync.RWMutex
	getInquisitorArgsForCall []struct {
		arg1 *cfclient.Config
	}
	getInquisitorReturns struct {
		result1 query.Inquisitor
		result2 error
	}
	getInquisitorReturnsOnCall map[int]struct {
		result1 query.Inquisitor
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInquisitorManager) GetHelper(arg1 *cfclient.Config) (change.InquisitorHelper, error) {
	fake.getHelperMutex.Lock()
	ret, specificReturn := fake.getHelperReturnsOnCall[len(fake.getHelperArgsForCall)]
	fake.getHelperArgsForCall = append(fake.getHelperArgsForCall, struct {
		arg1 *cfclient.Config
	}{arg1})
	fake.recordInvocation("GetHelper", []interface{}{arg1})
	fake.getHelperMutex.Unlock()
	if fake.GetHelperStub != nil {
		return fake.GetHelperStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getHelperReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInquisitorManager) GetHelperCallCount() int {
	fake.getHelperMutex.RLock()
	defer fake.getHelperMutex.RUnlock()
	return len(fake.getHelperArgsForCall)
}

func (fake *FakeInquisitorManager) GetHelperCalls(stub func(*cfclient.Config) (change.InquisitorHelper, error)) {
	fake.getHelperMutex.Lock()
	defer fake.getHelperMutex.Unlock()
	fake.GetHelperStub = stub
}

func (fake *FakeInquisitorManager) GetHelperArgsForCall(i int) *cfclient.Config {
	fake.getHelperMutex.RLock()
	defer fake.getHelperMutex.RUnlock()
	argsForCall := fake.getHelperArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInquisitorManager) GetHelperReturns(result1 change.InquisitorHelper, result2 error) {
	fake.getHelperMutex.Lock()
	defer fake.getHelperMutex.Unlock()
	fake.GetHelperStub = nil
	fake.getHelperReturns = struct {
		result1 change.InquisitorHelper
		result2 error
	}{result1, result2}
}

func (fake *FakeInquisitorManager) GetHelperReturnsOnCall(i int, result1 change.InquisitorHelper, result2 error) {
	fake.getHelperMutex.Lock()
	defer fake.getHelperMutex.Unlock()
	fake.GetHelperStub = nil
	if fake.getHelperReturnsOnCall == nil {
		fake.getHelperReturnsOnCall = make(map[int]struct {
			result1 change.InquisitorHelper
			result2 error
		})
	}
	fake.getHelperReturnsOnCall[i] = struct {
		result1 change.InquisitorHelper
		result2 error
	}{result1, result2}
}

func (fake *FakeInquisitorManager) GetInquisitor(arg1 *cfclient.Config) (query.Inquisitor, error) {
	fake.getInquisitorMutex.Lock()
	ret, specificReturn := fake.getInquisitorReturnsOnCall[len(fake.getInquisitorArgsForCall)]
	fake.getInquisitorArgsForCall = append(fake.getInquisitorArgsForCall, struct {
		arg1 *cfclient.Config
	}{arg1})
	fake.recordInvocation("GetInquisitor", []interface{}{arg1})
	fake.getInquisitorMutex.Unlock()
	if fake.GetInquisitorStub != nil {
		return fake.GetInquisitorStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInquisitorReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInquisitorManager) GetInquisitorCallCount() int {
	fake.getInquisitorMutex.RLock()
	defer fake.getInquisitorMutex.RUnlock()
	return len(fake.getInquisitorArgsForCall)
}

func (fake *FakeInquisitorManager) GetInquisitorCalls(stub func(*cfclient.Config) (query.Inquisitor, error)) {
	fake.getInquisitorMutex.Lock()
	defer fake.getInquisitorMutex.Unlock()
	fake.GetInquisitorStub = stub
}

func (fake *FakeInquisitorManager) GetInquisitorArgsForCall(i int) *cfclient.Config {
	fake.getInquisitorMutex.RLock()
	defer fake.getInquisitorMutex.RUnlock()
	argsForCall := fake.getInquisitorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInquisitorManager) GetInquisitorReturns(result1 query.Inquisitor, result2 error) {
	fake.getInquisitorMutex.Lock()
	defer fake.getInquisitorMutex.Unlock()
	fake.GetInquisitorStub = nil
	fake.getInquisitorReturns = struct {
		result1 query.Inquisitor
		result2 error
	}{result1, result2}
}

func (fake *FakeInquisitorManager) GetInquisitorReturnsOnCall(i int, result1 query.Inquisitor, result2 error) {
	fake.getInquisitorMutex.Lock()
	defer fake.getInquisitorMutex.Unlock()
	fake.GetInquisitorStub = nil
	if fake.getInquisitorReturnsOnCall == nil {
		fake.getInquisitorReturnsOnCall = make(map[int]struct {
			result1 query.Inquisitor
			result2 error
		})
	}
	fake.getInquisitorReturnsOnCall[i] = struct {
		result1 query.Inquisitor
		result2 error
	}{result1, result2}
}

func (fake *FakeInquisitorManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getHelperMutex.RLock()
	defer fake.getHelperMutex.RUnlock()
	fake.getInquisitorMutex.RLock()
	defer fake.getInquisitorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInquisitorManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ change.InquisitorManager = new(FakeInquisitorManager)
