// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	. "github.com/mike-carey/change-all-stacks/query"
	"fmt"

	fakes "github.com/mike-carey/change-all-stacks/query/fakes"
)

var _ = Describe(fmt.Sprintf("%sService", getAppString()), func() {

	var (
		storage    *Storage
		fakeClient *fakes.FakeCFClient
		service    *AppService
	)

	BeforeEach(func() {
		storage = GetStorage()
		fakeClient = GetFakeClient(storage)
		service = NewAppService(fakeClient, GinkgoWriter)
	})

	It(fmt.Sprintf("Should get all %s", getAppString()), func() {
		items, err := service.GetAllApps()
		Expect(err).To(BeNil())
		Expect(items).Should(ConsistOf(storage.Apps))
	})

	It(fmt.Sprintf("Should get %s by guid", getAppString()), func() {
		item, err := service.GetAppByGuid(fmt.Sprintf("%s-1", getAppString()))
		Expect(err).To(BeNil())
		Expect(item).Should(Equal(storage.Apps[0]))
	})

	It(fmt.Sprintf("Should get %s by name", getAppString()), func() {
		item, err := service.GetAppByName(fmt.Sprintf("%s-1", getAppString()))
		Expect(err).To(BeNil())
		Expect(item).To(Equal(storage.Apps[0]))
	})
})
