// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"fmt"
	"io"
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
)

type AppService struct {
	client      CFClient
	logger      io.Writer
	cacheList   []cfclient.App
	cacheMap    map[string]cfclient.App
	mutex       *sync.Mutex
	fullyLoaded bool
}

func NewAppService(client CFClient, logger io.Writer) *AppService {
	return &AppService{
		client:      client,
		logger:      logger,
		cacheList:   make([]cfclient.App, 0),
		cacheMap:    make(map[string]cfclient.App, 0),
		mutex:       &sync.Mutex{},
		fullyLoaded: false,
	}
}

func (s *AppService) logf(msg string, args ...interface{}) {
	s.logger.Write([]byte(fmt.Sprintf(msg+"\n", args...)))
}

func (s *AppService) lock() {
	s.logf("Locking %T", s)
	s.mutex.Lock()
	s.logf("Locked %T", s)
}

func (s *AppService) unlock() {
	s.logf("Unlocking %T", s)
	s.mutex.Unlock()
	s.logf("Unlocked %T", s)
}

func (s *AppService) GetAllApps() ([]cfclient.App, error) {
	s.lock()

	if !s.fullyLoaded {
		s.logf("%T is not already fully loaded", s)
		items, err := s.client.ListApps()
		if err != nil {
			return nil, err
		}

		s.logf("Writing cache list for %T", s)
		s.cacheList = items

		go func() {
			defer s.unlock()

			s.logf("Writing cache map for %T", s)
			for _, item := range items {
				s.cacheMap[item.Guid] = item
			}
		}()
	} else {
		defer s.unlock()
	}

	return s.cacheList, nil
}

func (s *AppService) GetAppByGuid(guid string) (cfclient.App, error) {
	s.lock()
	defer s.unlock()

	if item, ok := s.cacheMap[guid]; ok {
		s.logf("Found a cached %T with a guid of %s", item, guid)
		return item, nil
	}

	if s.fullyLoaded {
		s.logf("%T is already fully loaded but did not find %s in cacheMap", s, guid)
		item := cfclient.App{}
		return item, NewNotFoundError(item, "guid", guid)
	}

	s.logf("Did not find cached %T and %T is not fully loaded, querying by guid: %s", cfclient.App{}, s, guid)
	i, err := s.client.GetAppByGuid(guid)
	if err != nil {
		return cfclient.App{}, nil
	}

	s.logf("Saving off a single %T to the cacheMap with guid: %s", i, i.Guid)
	s.cacheMap[i.Guid] = i
	return i, nil
}

func (s *AppService) GetAppByName(name string) (cfclient.App, error) {
	items, err := s.GetAllApps()
	if err != nil {
		return cfclient.App{}, err
	}

	s.lock()
	defer s.unlock()

	for _, item := range items {
		if item.Name == name {
			return item, nil
		}
	}

	item := cfclient.App{}
	return item, NewNotFoundError(item, "name", name)
}

// Proxy all functions onto the inquisitor struct
func (i *inquisitor) GetAllApps() ([]cfclient.App, error) {
	return i.getAppService().GetAllApps()
}

func (i *inquisitor) GetAppByGuid(guid string) (cfclient.App, error) {
	return i.getAppService().GetAppByGuid(guid)
}

func (i *inquisitor) GetAppByName(name string) (cfclient.App, error) {
	return i.getAppService().GetAppByName(name)
}
