// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/change-all-stacks/logger"
)

type AppService struct {
	client      CFClient
	cacheList   []cfclient.App
	cacheMap    map[string]cfclient.App
	mutex       *sync.Mutex
	fullyLoaded bool
}

func NewAppService(client CFClient) *AppService {
	return &AppService{
		client:      client,
		cacheList:   make([]cfclient.App, 0),
		cacheMap:    make(map[string]cfclient.App, 0),
		mutex:       &sync.Mutex{},
		fullyLoaded: false,
	}
}

func (s *AppService) lock() {
	logger.Debugf("Locking %T", s)
	s.mutex.Lock()
	logger.Debugf("Locked %T", s)
}

func (s *AppService) unlock() {
	logger.Debugf("Unlocking %T", s)
	s.mutex.Unlock()
	logger.Debugf("Unlocked %T", s)
}

func (s *AppService) GetAllApps() ([]cfclient.App, error) {
	s.lock()

	if !s.fullyLoaded {
		logger.Debugf("%T is not already fully loaded", s)
		items, err := s.client.ListApps()
		if err != nil {
			return nil, err
		}

		logger.Debugf("Writing cache list for %T", s)
		s.cacheList = items

		go func(s *AppService, items []cfclient.App) {
			defer s.unlock()

			logger.Debugf("Writing cache map for %T", s)
			for _, item := range items {
				s.cacheMap[item.Guid] = item
			}
		}(s, items)
	} else {
		defer s.unlock()
	}

	return s.cacheList, nil
}

func (s *AppService) GetAppByGuid(guid string) (cfclient.App, error) {
	s.lock()
	defer s.unlock()

	if item, ok := s.cacheMap[guid]; ok {
		logger.Debugf("Found a cached %T with a guid of %s", item, guid)
		return item, nil
	}

	if s.fullyLoaded {
		logger.Debugf("%T is already fully loaded but did not find %s in cacheMap", s, guid)
		item := cfclient.App{}
		return item, NewNotFoundError(item, "guid", guid)
	}

	logger.Debugf("Did not find cached %T and %T is not fully loaded, querying by guid: %s", cfclient.App{}, s, guid)
	i, err := s.client.GetAppByGuid(guid)
	if err != nil {
		return cfclient.App{}, nil
	}

	logger.Debugf("Saving off a single %T to the cacheMap with guid: %s", i, i.Guid)
	s.cacheMap[i.Guid] = i
	return i, nil
}

func (s *AppService) GetAppByName(name string) (cfclient.App, error) {
	items, err := s.GetAllApps()
	if err != nil {
		return cfclient.App{}, err
	}

	s.lock()
	defer s.unlock()

	for _, item := range items {
		if item.Name == name {
			return item, nil
		}
	}

	item := cfclient.App{}
	return item, NewNotFoundError(item, "name", name)
}

// Proxy all functions onto the inquisitor struct
func (i *inquisitor) GetAllApps() ([]cfclient.App, error) {
	return i.getAppService().GetAllApps()
}

func (i *inquisitor) GetAppByGuid(guid string) (cfclient.App, error) {
	return i.getAppService().GetAppByGuid(guid)
}

func (i *inquisitor) GetAppByName(name string) (cfclient.App, error) {
	return i.getAppService().GetAppByName(name)
}
