// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/pkg/errors"
)

func BuildpackGroupBy(items []cfclient.Buildpack, getKey func(cfclient.Buildpack) (string, error)) (map[string][]cfclient.Buildpack, error) {
	pool := make(map[string][]cfclient.Buildpack)

	for _, item := range items {
		key, err := getKey(item)
		if err != nil {
			return pool, errors.Wrap(err, "Could not get key for item")
		}

		if _, ok := pool[key]; !ok {
			pool[key] = make([]cfclient.Buildpack, 0)
		}

		pool[key] = append(pool[key], item)
	}

	return pool, nil
}
