// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/change-all-stacks/logger"
)

type OrgService struct {
	client      CFClient
	cacheList   []cfclient.Org
	cacheMap    map[string]cfclient.Org
	mutex       *sync.Mutex
	fullyLoaded bool
}

func NewOrgService(client CFClient) *OrgService {
	return &OrgService{
		client:      client,
		cacheList:   make([]cfclient.Org, 0),
		cacheMap:    make(map[string]cfclient.Org, 0),
		mutex:       &sync.Mutex{},
		fullyLoaded: false,
	}
}

func (s *OrgService) lock() {
	logger.Debugf("Locking %T", s)
	s.mutex.Lock()
	logger.Debugf("Locked %T", s)
}

func (s *OrgService) unlock() {
	logger.Debugf("Unlocking %T", s)
	s.mutex.Unlock()
	logger.Debugf("Unlocked %T", s)
}

func (s *OrgService) GetAllOrgs() ([]cfclient.Org, error) {
	s.lock()

	if !s.fullyLoaded {
		logger.Debugf("%T is not already fully loaded", s)
		items, err := s.client.ListOrgs()
		if err != nil {
			return nil, err
		}

		logger.Debugf("Writing cache list for %T", s)
		s.cacheList = items

		go func(s *OrgService, items []cfclient.Org) {
			defer s.unlock()

			logger.Debugf("Writing cache map for %T", s)
			for _, item := range items {
				s.cacheMap[item.Guid] = item
			}
		}(s, items)
	} else {
		defer s.unlock()
	}

	return s.cacheList, nil
}

func (s *OrgService) GetOrgByGuid(guid string) (cfclient.Org, error) {
	s.lock()
	defer s.unlock()

	if item, ok := s.cacheMap[guid]; ok {
		logger.Debugf("Found a cached %T with a guid of %s", item, guid)
		return item, nil
	}

	if s.fullyLoaded {
		logger.Debugf("%T is already fully loaded but did not find %s in cacheMap", s, guid)
		item := cfclient.Org{}
		return item, NewNotFoundError(item, "guid", guid)
	}

	logger.Debugf("Did not find cached %T and %T is not fully loaded, querying by guid: %s", cfclient.Org{}, s, guid)
	i, err := s.client.GetOrgByGuid(guid)
	if err != nil {
		return cfclient.Org{}, nil
	}

	logger.Debugf("Saving off a single %T to the cacheMap with guid: %s", i, i.Guid)
	s.cacheMap[i.Guid] = i
	return i, nil
}

func (s *OrgService) GetOrgByName(name string) (cfclient.Org, error) {
	items, err := s.GetAllOrgs()
	if err != nil {
		return cfclient.Org{}, err
	}

	s.lock()
	defer s.unlock()

	for _, item := range items {
		if item.Name == name {
			return item, nil
		}
	}

	item := cfclient.Org{}
	return item, NewNotFoundError(item, "name", name)
}

// Proxy all functions onto the inquisitor struct
func (i *inquisitor) GetAllOrgs() ([]cfclient.Org, error) {
	return i.getOrgService().GetAllOrgs()
}

func (i *inquisitor) GetOrgByGuid(guid string) (cfclient.Org, error) {
	return i.getOrgService().GetOrgByGuid(guid)
}

func (i *inquisitor) GetOrgByName(name string) (cfclient.Org, error) {
	return i.getOrgService().GetOrgByName(name)
}
