// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/change-all-stacks/logger"
)

type SpaceService struct {
	client      CFClient
	cacheList   []cfclient.Space
	cacheMap    map[string]cfclient.Space
	mutex       *sync.Mutex
	fullyLoaded bool
}

func NewSpaceService(client CFClient) *SpaceService {
	return &SpaceService{
		client:      client,
		cacheList:   make([]cfclient.Space, 0),
		cacheMap:    make(map[string]cfclient.Space, 0),
		mutex:       &sync.Mutex{},
		fullyLoaded: false,
	}
}

func (s *SpaceService) lock() {
	logger.Debugf("Locking %T", s)
	s.mutex.Lock()
	logger.Debugf("Locked %T", s)
}

func (s *SpaceService) unlock() {
	logger.Debugf("Unlocking %T", s)
	s.mutex.Unlock()
	logger.Debugf("Unlocked %T", s)
}

func (s *SpaceService) GetAllSpaces() ([]cfclient.Space, error) {
	s.lock()

	if !s.fullyLoaded {
		logger.Debugf("%T is not already fully loaded", s)
		items, err := s.client.ListSpaces()
		if err != nil {
			return nil, err
		}

		logger.Debugf("Writing cache list for %T", s)
		s.cacheList = items

		go func(s *SpaceService, items []cfclient.Space) {
			defer s.unlock()

			logger.Debugf("Writing cache map for %T", s)
			for _, item := range items {
				s.cacheMap[item.Guid] = item
			}
		}(s, items)
	} else {
		defer s.unlock()
	}

	return s.cacheList, nil
}

func (s *SpaceService) GetSpaceByGuid(guid string) (cfclient.Space, error) {
	s.lock()
	defer s.unlock()

	if item, ok := s.cacheMap[guid]; ok {
		logger.Debugf("Found a cached %T with a guid of %s", item, guid)
		return item, nil
	}

	if s.fullyLoaded {
		logger.Debugf("%T is already fully loaded but did not find %s in cacheMap", s, guid)
		item := cfclient.Space{}
		return item, NewNotFoundError(item, "guid", guid)
	}

	logger.Debugf("Did not find cached %T and %T is not fully loaded, querying by guid: %s", cfclient.Space{}, s, guid)
	i, err := s.client.GetSpaceByGuid(guid)
	if err != nil {
		return cfclient.Space{}, nil
	}

	logger.Debugf("Saving off a single %T to the cacheMap with guid: %s", i, i.Guid)
	s.cacheMap[i.Guid] = i
	return i, nil
}

func (s *SpaceService) GetSpaceByName(name string) (cfclient.Space, error) {
	items, err := s.GetAllSpaces()
	if err != nil {
		return cfclient.Space{}, err
	}

	s.lock()
	defer s.unlock()

	for _, item := range items {
		if item.Name == name {
			return item, nil
		}
	}

	item := cfclient.Space{}
	return item, NewNotFoundError(item, "name", name)
}

// Proxy all functions onto the inquisitor struct
func (i *inquisitor) GetAllSpaces() ([]cfclient.Space, error) {
	return i.getSpaceService().GetAllSpaces()
}

func (i *inquisitor) GetSpaceByGuid(guid string) (cfclient.Space, error) {
	return i.getSpaceService().GetSpaceByGuid(guid)
}

func (i *inquisitor) GetSpaceByName(name string) (cfclient.Space, error) {
	return i.getSpaceService().GetSpaceByName(name)
}
