// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	. "github.com/mike-carey/change-all-stacks/query"
	"fmt"

	fakes "github.com/mike-carey/change-all-stacks/query/fakes"
)

var _ = Describe(fmt.Sprintf("%sService", getStackString()), func() {

	var (
		storage    *Storage
		fakeClient *fakes.FakeCFClient
		service    *StackService
	)

	BeforeEach(func() {
		storage = GetStorage()
		fakeClient = GetFakeClient(storage)
		service = NewStackService(fakeClient, GinkgoWriter)
	})

	It(fmt.Sprintf("Should get all %s", getStackString()), func() {
		items, err := service.GetAllStacks()
		Expect(err).To(BeNil())
		Expect(items).Should(ConsistOf(storage.Stacks))
	})

	It(fmt.Sprintf("Should get %s by guid", getStackString()), func() {
		item, err := service.GetStackByGuid(fmt.Sprintf("%s-1", getStackString()))
		Expect(err).To(BeNil())
		Expect(item).Should(Equal(storage.Stacks[0]))
	})

	It(fmt.Sprintf("Should get %s by name", getStackString()), func() {
		item, err := service.GetStackByName(fmt.Sprintf("%s-1", getStackString()))
		Expect(err).To(BeNil())
		Expect(item).To(Equal(storage.Stacks[0]))
	})
})
