// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	. "github.com/mike-carey/change-all-stacks/query"
	"fmt"
	"strings"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
)

var _ = Describe(fmt.Sprintf("%sFilterBy", getStackString()), func() {

	var (
		items []cfclient.Stack
	)

	BeforeEach(func() {
		items = []cfclient.Stack{
			cfclient.Stack{
				Guid: fmt.Sprintf("%s-%d-%d", getStackString(), 1, 1),
			},
			cfclient.Stack{
				Guid: fmt.Sprintf("%s-%d-%d", getStackString(), 1, 2),
			},
			cfclient.Stack{
				Guid: fmt.Sprintf("%s-%d-%d", getStackString(), 2, 1),
			},
			cfclient.Stack{
				Guid: fmt.Sprintf("%s-%d-%d", getStackString(), 2, 2),
			},
		}
	})

	It("Should filter by first number", func() {
		By("Equaling 1")
		i1, e1 := StackFilterBy(items, func(item cfclient.Stack) (bool, error) {
			s := strings.Split(item.Guid, "-")
			return s[1] == "1", nil
		})

		Expect(e1).To(BeNil())
		Expect(i1).Should(HaveLen(2))
		Expect(i1).Should(ConsistOf(items[0], items[1]))

		By("Equaling 2")
		i2, e2 := StackFilterBy(items, func(item cfclient.Stack) (bool, error) {
			s := strings.Split(item.Guid, "-")
			return s[1] == "2", nil
		})
		Expect(e2).To(BeNil())
		Expect(i2).Should(HaveLen(2))
		Expect(i2).Should(ConsistOf(items[2], items[3]))
	})

	It("Should filter by second number", func() {
		By("Equaling 1")
		i1, e1 := StackFilterBy(items, func(item cfclient.Stack) (bool, error) {
			s := strings.Split(item.Guid, "-")
			return s[2] == "1", nil
		})

		Expect(e1).To(BeNil())
		Expect(i1).Should(HaveLen(2))
		Expect(i1).Should(ConsistOf(items[0], items[2]))

		By("Equaling 2")
		i2, e2 := StackFilterBy(items, func(item cfclient.Stack) (bool, error) {
			s := strings.Split(item.Guid, "-")
			return s[2] == "2", nil
		})
		Expect(e2).To(BeNil())
		Expect(i2).Should(HaveLen(2))
		Expect(i2).Should(ConsistOf(items[1], items[3]))
	})
})
