// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"fmt"
	"io"
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
)

type StackService struct {
	client      CFClient
	logger      io.Writer
	cacheList   []cfclient.Stack
	cacheMap    map[string]cfclient.Stack
	mutex       *sync.Mutex
	fullyLoaded bool
}

func NewStackService(client CFClient, logger io.Writer) *StackService {
	return &StackService{
		client:      client,
		logger:      logger,
		cacheList:   make([]cfclient.Stack, 0),
		cacheMap:    make(map[string]cfclient.Stack, 0),
		mutex:       &sync.Mutex{},
		fullyLoaded: false,
	}
}

func (s *StackService) logf(msg string, args ...interface{}) {
	s.logger.Write([]byte(fmt.Sprintf(msg+"\n", args...)))
}

func (s *StackService) lock() {
	s.logf("Locking %T", s)
	s.mutex.Lock()
	s.logf("Locked %T", s)
}

func (s *StackService) unlock() {
	s.logf("Unlocking %T", s)
	s.mutex.Unlock()
	s.logf("Unlocked %T", s)
}

func (s *StackService) GetAllStacks() ([]cfclient.Stack, error) {
	s.lock()

	if !s.fullyLoaded {
		s.logf("%T is not already fully loaded", s)
		items, err := s.client.ListStacks()
		if err != nil {
			return nil, err
		}

		s.logf("Writing cache list for %T", s)
		s.cacheList = items

		go func() {
			defer s.unlock()

			s.logf("Writing cache map for %T", s)
			for _, item := range items {
				s.cacheMap[item.Guid] = item
			}
		}()
	} else {
		defer s.unlock()
	}

	return s.cacheList, nil
}

func (s *StackService) GetStackByGuid(guid string) (cfclient.Stack, error) {
	s.lock()
	//defer s.unlock()

	if item, ok := s.cacheMap[guid]; ok {
		s.logf("Found a cached %T with a guid of %s", item, guid)
		return item, nil
	}

	if s.fullyLoaded {
		s.logf("%T is already fully loaded but did not find %s in cacheMap", s, guid)
		item := cfclient.Stack{}
		return item, NewNotFoundError(item, "guid", guid)
	}

	s.logf("Did not find cached %T and %T is not fully loaded, querying by guid: %s", cfclient.Stack{}, s, guid)
	s.unlock()
	i, err := s.getStackByGuid(guid)
	if err != nil {
		return cfclient.Stack{}, nil
	}

	s.logf("Saving off a single %T to the cacheMap with guid: %s", i, i.Guid)
	s.cacheMap[i.Guid] = i
	return i, nil
}

func (s *StackService) GetStackByName(name string) (cfclient.Stack, error) {
	items, err := s.GetAllStacks()
	if err != nil {
		return cfclient.Stack{}, err
	}

	s.lock()
	defer s.unlock()

	for _, item := range items {
		if item.Name == name {
			return item, nil
		}
	}

	item := cfclient.Stack{}
	return item, NewNotFoundError(item, "name", name)
}

// Proxy all functions onto the inquisitor struct
func (i *inquisitor) GetAllStacks() ([]cfclient.Stack, error) {
	return i.getStackService().GetAllStacks()
}

func (i *inquisitor) GetStackByGuid(guid string) (cfclient.Stack, error) {
	return i.getStackService().GetStackByGuid(guid)
}

func (i *inquisitor) GetStackByName(name string) (cfclient.Stack, error) {
	return i.getStackService().GetStackByName(name)
}

// Worksaround until merge: https://github.com/cloudfoundry-community/go-cfclient/pull/234
func (s *StackService) getStackByGuid(guid string) (cfclient.Stack, error) {
	// Grab all stacks and find the one that has the desired guid
	stacks, err := s.GetAllStacks()
	if err != nil {
		return cfclient.Stack{}, nil
	}

	for _, stack := range stacks {
		if stack.Guid == guid {
			return stack, nil
		}
	}

	return cfclient.Stack{}, fmt.Errorf("Could not find stack with guid: '%s'", guid)
}
